-- Setup SQL for Photo Gallery
-- Run these commands in your MySQL database

-- 1. Create the database (if not exists)
CREATE DATABASE IF NOT EXISTS u324425198_Photos;

-- 2. Use the database
USE u324425198_Photos;

-- 3. Create albums table
CREATE TABLE IF NOT EXISTS albums (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    cover_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. Create photos table
CREATE TABLE IF NOT EXISTS photos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    album_id INT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uploader VARCHAR(100),
    ip_address VARCHAR(45),
    FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE SET NULL
);

-- 5. Create users table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Create photo_feedback table
CREATE TABLE IF NOT EXISTS photo_feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    photo_filename VARCHAR(255) NOT NULL,
    rating TINYINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    user_ip VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_photo_filename (photo_filename),
    INDEX idx_created_at (created_at)
);

-- 7. Insert default admin user
-- Note: Password is hashed using PHP's password_hash()
-- The actual hash will be generated by the PHP code
INSERT IGNORE INTO users (username, password, is_admin) VALUES ('Khanh', '$2y$10$example.hash.here', TRUE);